// JS/Fullstack/quizlytics/src/components/shared/Header.tsx
import Link from "next/link"
import { useSession,signOut } from 'next-auth/react'
import RequireAuth from "./RequireAuth"
import HeaderMenu from "../HeaderMenu"

const Header = () => {

  return (
    <header
    className="w-full h-[10vh]"
    >
        <nav
        className="px-6 py-3 w-full h-full flex flex-row justify-between items-center"
        >
            <Link href="/">
              <h2
              className="text-xl font-extrabold text-primary-dark"
              >Quizlytics</h2>
            </Link>
            <div className="max-sm:hidden">
              <RequireAuth >
                <button onClick={() => signOut()}>
                  Logout
                </button>
              </RequireAuth>
            </div>
            <HeaderMenu></HeaderMenu>
        </nav>
    </header>
  )
}

export default Header

// JS/Fullstack/quizlytics_failed/components/Header.vue
<template>
    <header
    class="w-full h-[10vh] shadow-md"
    >
        <nav
        class="px-6 py-3 w-full h-full flex flex-row justify-between items-center"
        >
            <NuxtLink to="/">
              <h2
              class="text-xl font-extrabold text-primary-dark"
              >Quizlytics</h2>
            </NuxtLink>
            <button type="button"
            class="text-primary hover:text-primary-dark sm:hidden"
            >
                burger
            </button>
        </nav>
    </header>
</template>
